import type { AdminLoginResult, AdminUser } from '@mall/shared-types';

export type {
  AdminOrderQuery,
  AdminAfterSaleQuery,
  AdminProductQuery,
  AdminLoginInput,
  AdminProfile,
  AdminUserQuery,
  AfterSale,
  AfterSaleActorType,
  AfterSaleListResult,
  AfterSaleLog,
  AfterSaleRefundSnapshot,
  AfterSaleStatus,
  AfterSaleType,
  ApproveAfterSaleInput,
  Category,
  CategoryInput,
  Coupon,
  CouponInput,
  CouponQuery,
  CouponStatus,
  ConfirmReturnReceivedInput,
  DashboardOverview,
  HomeBanner,
  HomeBannerInput,
  Order,
  OrderLogisticsTraceStatus,
  OrderListResult,
  OrderStatus,
  PointRedeemRules,
  Product,
  ProductImage,
  ProductImageInput,
  ProductInput,
  ProductSku,
  ProductSkuInput,
  ProductStatus,
  RefundStatus,
  RejectAfterSaleInput,
  ShipOrderInput,
  UpdateCategoryInput,
  UpdateHomeBannersInput,
  UploadResult,
} from '@mall/shared-types';

export type User = AdminUser;
export type LoginResult = AdminLoginResult;
