import type { MiniappLoginResult } from '@mall/shared-types';

export type {
  AddCartItemInput,
  AddressInput,
  AfterSale,
  AfterSaleActorType,
  AfterSaleListResult,
  AfterSaleLog,
  AfterSaleStatus,
  AfterSaleSummary,
  AfterSaleType,
  Cart,
  CartItem,
  CartItemProduct,
  CartItemSku,
  CartSummary,
  Category,
  Coupon,
  CreateAfterSaleInput,
  CreateOrderInput,
  HomeBanner,
  MiniappUser,
  Order,
  OrderItem,
  OrderLogisticsTrace,
  OrderLogisticsTraceStatus,
  OrderListResult,
  OrderStatus,
  Payment,
  PaymentStatus,
  PointLedger,
  PointLedgerType,
  Product,
  ProductImage,
  ProductQuery,
  ProductSku,
  ProductStatus,
  RefundStatus,
  SubmitReturnLogisticsInput,
  UpdateAddressInput,
  UserAddress,
  UserCoupon,
  UserCouponStatus,
  UserOrderQuery,
  WechatNotifyInput,
  WechatNotifyResult,
  WechatPayParams,
  WechatPrepayResult,
  WxLoginInput,
} from '@mall/shared-types';

export type LoginResult = MiniappLoginResult;
