import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, '../../..');
const templatePath = resolve(repoRoot, 'docs/p5-real-payment-test-record-template.md');
const defaultRecordDir = resolve(repoRoot, 'docs/records');

function formatDate(date = new Date()) {
  const parts = new Intl.DateTimeFormat('en', {
    day: '2-digit',
    month: '2-digit',
    timeZone: 'Asia/Shanghai',
    year: 'numeric',
  }).formatToParts(date);
  const getPart = (type: string) => parts.find((part) => part.type === type)?.value;

  return `${getPart('year')}-${getPart('month')}-${getPart('day')}`;
}

function safeValue(value: string | undefined) {
  return value && value.trim().length > 0 ? value : '待填写';
}

function suffix(value: string | undefined, length: number) {
  if (!value) {
    return '待填写';
  }

  return value.slice(-length);
}

function buildEnvironmentSummary() {
  const apiBaseUrl = safeValue(process.env.INTEGRATION_API_BASE_URL);
  const notifyUrl = safeValue(process.env.WECHAT_PAY_NOTIFY_URL);

  return [
    '## 环境摘要',
    '',
    '| 项目 | 内容 |',
    '| ---- | ---- |',
    `| 环境 | ${safeValue(process.env.INTEGRATION_RECORD_ENV)} |`,
    `| API 域名 | ${apiBaseUrl} |`,
    `| 小程序 appId 后 6 位 | ${suffix(process.env.WECHAT_MINIAPP_APP_ID, 6)} |`,
    `| 商户号后 6 位 | ${suffix(process.env.WECHAT_PAY_MCH_ID, 6)} |`,
    `| WECHAT_LOGIN_MODE | ${safeValue(process.env.WECHAT_LOGIN_MODE)} |`,
    `| WECHAT_PAY_MODE | ${safeValue(process.env.WECHAT_PAY_MODE)} |`,
    `| TARO_APP_PAYMENT_MODE | ${safeValue(process.env.TARO_APP_PAYMENT_MODE)} |`,
    `| WECHAT_PAY_NOTIFY_URL | ${notifyUrl} |`,
    '',
  ].join('\n');
}

function resolveFromRepo(path: string) {
  return resolve(repoRoot, path);
}

async function run() {
  const recordDate = process.env.INTEGRATION_RECORD_DATE ?? formatDate();
  const recordEnv = process.env.INTEGRATION_RECORD_ENV ?? 'dev';
  const recordDir = process.env.INTEGRATION_RECORD_DIR
    ? resolveFromRepo(process.env.INTEGRATION_RECORD_DIR)
    : defaultRecordDir;
  const recordPath = resolveFromRepo(
    process.env.INTEGRATION_RECORD_PATH ??
      resolve(recordDir, `${recordDate}-wechat-pay-real-test-${recordEnv}.md`),
  );
  const shouldOverwrite = process.env.INTEGRATION_RECORD_OVERWRITE === '1';

  if (existsSync(recordPath) && !shouldOverwrite) {
    throw new Error(
      `Record already exists: ${recordPath}. Set INTEGRATION_RECORD_OVERWRITE=1 to overwrite.`,
    );
  }

  const template = await readFile(templatePath, 'utf8');
  const content = [
    '<!-- Generated by pnpm integration:record. Do not write secrets, private keys, full tokens, or full signatures into this file. -->',
    '',
    template
      .replace('# P5 真实支付联调记录模板', '# P5 真实支付联调记录')
      .replace('记录时间：2026-05-29', `记录时间：${recordDate}`)
      .replace('## 基本信息', `${buildEnvironmentSummary()}\n## 基本信息`)
      .replace(
        '本文档是模板。真实联调时复制一份，以日期和环境命名，例如：',
        '本文档用于记录一次真实微信支付联调。',
      )
      .replace(
        ['```text', 'docs/records/2026-05-29-wechat-pay-real-test.md', '```', ''].join('\n'),
        '',
      ),
  ].join('\n');

  await mkdir(dirname(recordPath), { recursive: true });
  await writeFile(recordPath, content);

  console.log(`Real payment integration record created: ${recordPath}`);
  console.log('Next suggested check: INTEGRATION_REQUIRE_REAL=1 pnpm integration:check');
}

run().catch((error: unknown) => {
  console.error(
    `Failed to create real payment integration record: ${
      error instanceof Error ? error.message : error
    }`,
  );
  process.exitCode = 1;
});
